import { integer, primaryKey, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = { createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()), updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()) };

export const users = sqliteTable("users", { id: text("id").primaryKey(), email: text("email").notNull().unique(), username: text("username").notNull().unique(), passwordHash: text("password_hash"), role: text("role", { enum: ["user", "admin"] }).notNull().default("user"), ...timestamps });
export const profiles = sqliteTable("profiles", { userId: text("user_id").primaryKey().references(() => users.id, { onDelete: "cascade" }), displayName: text("display_name").notNull(), bio: text("bio"), avatarUrl: text("avatar_url"), coverUrl: text("cover_url"), location: text("location"), language: text("language").default("en"), verified: integer("verified", { mode: "boolean" }).default(false), ...timestamps });
export const follows = sqliteTable("follows", { followerId: text("follower_id").references(() => users.id, { onDelete: "cascade" }).notNull(), followingId: text("following_id").references(() => users.id, { onDelete: "cascade" }).notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()) }, (t) => [primaryKey({ columns: [t.followerId, t.followingId] })]);
export const genres = sqliteTable("genres", { id: integer("id").primaryKey(), name: text("name").notNull().unique(), slug: text("slug").notNull().unique() });
export const countries = sqliteTable("countries", { id: integer("id").primaryKey(), name: text("name").notNull(), isoCode: text("iso_code").notNull().unique() });
export const languages = sqliteTable("languages", { id: integer("id").primaryKey(), name: text("name").notNull(), isoCode: text("iso_code").notNull().unique() });
export const titles = sqliteTable("titles", { id: text("id").primaryKey(), tmdbId: integer("tmdb_id"), type: text("type", { enum: ["movie", "series"] }).notNull(), title: text("title").notNull(), originalTitle: text("original_title"), overview: text("overview"), posterPath: text("poster_path"), backdropPath: text("backdrop_path"), releaseDate: text("release_date"), runtime: integer("runtime"), certification: text("certification"), externalRating: real("external_rating"), popularity: real("popularity"), trailerKey: text("trailer_key"), ...timestamps }, (t) => [uniqueIndex("titles_tmdb_type_idx").on(t.tmdbId, t.type)]);
export const movieGenres = sqliteTable("movie_genres", { titleId: text("title_id").references(() => titles.id, { onDelete: "cascade" }).notNull(), genreId: integer("genre_id").references(() => genres.id, { onDelete: "cascade" }).notNull() }, (t) => [primaryKey({ columns: [t.titleId, t.genreId] })]);
export const movieCountries = sqliteTable("movie_countries", { titleId: text("title_id").references(() => titles.id, { onDelete: "cascade" }).notNull(), countryId: integer("country_id").references(() => countries.id, { onDelete: "cascade" }).notNull() }, (t) => [primaryKey({ columns: [t.titleId, t.countryId] })]);
export const movieLanguages = sqliteTable("movie_languages", { titleId: text("title_id").references(() => titles.id, { onDelete: "cascade" }).notNull(), languageId: integer("language_id").references(() => languages.id, { onDelete: "cascade" }).notNull() }, (t) => [primaryKey({ columns: [t.titleId, t.languageId] })]);
export const posts = sqliteTable("posts", { id: text("id").primaryKey(), authorId: text("author_id").references(() => users.id, { onDelete: "cascade" }).notNull(), titleId: text("title_id").references(() => titles.id), body: text("body").notNull(), visibility: text("visibility", { enum: ["public", "followers", "private"] }).notNull().default("public"), spoiler: integer("spoiler", { mode: "boolean" }).notNull().default(false), commentsEnabled: integer("comments_enabled", { mode: "boolean" }).notNull().default(true), ...timestamps });
export const postImages = sqliteTable("post_images", { id: text("id").primaryKey(), postId: text("post_id").references(() => posts.id, { onDelete: "cascade" }).notNull(), url: text("url").notNull(), sortOrder: integer("sort_order").notNull().default(0) });
export const reviews = sqliteTable("reviews", { id: text("id").primaryKey(), postId: text("post_id").references(() => posts.id, { onDelete: "cascade" }).notNull().unique(), titleId: text("title_id").references(() => titles.id, { onDelete: "cascade" }).notNull(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), rating: integer("rating").notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()) });
export const postLikes = sqliteTable("post_likes", { postId: text("post_id").references(() => posts.id, { onDelete: "cascade" }).notNull(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()) }, (t) => [primaryKey({ columns: [t.postId, t.userId] })]);
export const postComments = sqliteTable("post_comments", { id: text("id").primaryKey(), postId: text("post_id").references(() => posts.id, { onDelete: "cascade" }).notNull(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), body: text("body").notNull(), parentId: text("parent_id"), ...timestamps });
export const postShares = sqliteTable("post_shares", { id: text("id").primaryKey(), postId: text("post_id").references(() => posts.id, { onDelete: "cascade" }).notNull(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()) });
export const savedMovies = sqliteTable("saved_movies", { userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), titleId: text("title_id").references(() => titles.id, { onDelete: "cascade" }).notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()) }, (t) => [primaryKey({ columns: [t.userId, t.titleId] })]);
export const watchlist = sqliteTable("watchlist", { userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), titleId: text("title_id").references(() => titles.id, { onDelete: "cascade" }).notNull(), status: text("status", { enum: ["planned", "watching", "watched"] }).notNull().default("planned"), createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()) }, (t) => [primaryKey({ columns: [t.userId, t.titleId] })]);
export const userMovieInteractions = sqliteTable("user_movie_interactions", { userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), titleId: text("title_id").references(() => titles.id, { onDelete: "cascade" }).notNull(), interested: integer("interested", { mode: "boolean" }).default(false), reminder: integer("reminder", { mode: "boolean" }).default(false), updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()) }, (t) => [primaryKey({ columns: [t.userId, t.titleId] })]);
export const notifications = sqliteTable("notifications", { id: text("id").primaryKey(), recipientId: text("recipient_id").references(() => users.id, { onDelete: "cascade" }).notNull(), actorId: text("actor_id").references(() => users.id, { onDelete: "cascade" }), type: text("type", { enum: ["like", "comment", "follow", "mention", "rating"] }).notNull(), entityId: text("entity_id"), read: integer("read", { mode: "boolean" }).notNull().default(false), createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()) });
export const shoutboxMessages = sqliteTable("shoutbox_messages", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), type: text("type", { enum: ["text", "image", "voice"] }).notNull().default("text"), body: text("body"), mediaUrl: text("media_url"), duration: integer("duration"), createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()) });
export const shoutboxReactions = sqliteTable("shoutbox_reactions", { messageId: text("message_id").references(() => shoutboxMessages.id, { onDelete: "cascade" }).notNull(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), reaction: text("reaction").notNull().default("love") }, (t) => [primaryKey({ columns: [t.messageId, t.userId] })]);
