-- SCENORA Supabase/PostgreSQL schema
-- Paste this entire file into Supabase Dashboard > SQL Editor > New query > Run.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  username text not null unique check (username ~ '^[a-z0-9_]{3,30}$'),
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  user_id uuid primary key references public.users(id) on delete cascade,
  display_name text not null,
  bio text,
  avatar_url text,
  cover_url text,
  location text,
  language text not null default 'en',
  verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.genres (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique
);

create table if not exists public.countries (
  id bigint generated by default as identity primary key,
  name text not null,
  iso_code text not null unique
);

create table if not exists public.languages (
  id bigint generated by default as identity primary key,
  name text not null,
  iso_code text not null unique
);

create table if not exists public.titles (
  id uuid primary key default gen_random_uuid(),
  tmdb_id bigint,
  imdb_id text,
  type text not null check (type in ('movie', 'series')),
  title text not null,
  original_title text,
  overview text,
  poster_path text,
  backdrop_path text,
  release_date date,
  runtime integer check (runtime is null or runtime > 0),
  certification text,
  external_rating numeric(3,1),
  popularity numeric,
  trailer_key text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tmdb_id, type)
);

create table if not exists public.movie_genres (
  title_id uuid not null references public.titles(id) on delete cascade,
  genre_id bigint not null references public.genres(id) on delete cascade,
  primary key (title_id, genre_id)
);

create table if not exists public.movie_countries (
  title_id uuid not null references public.titles(id) on delete cascade,
  country_id bigint not null references public.countries(id) on delete cascade,
  primary key (title_id, country_id)
);

create table if not exists public.movie_languages (
  title_id uuid not null references public.titles(id) on delete cascade,
  language_id bigint not null references public.languages(id) on delete cascade,
  primary key (title_id, language_id)
);

create table if not exists public.follows (
  follower_id uuid not null references public.users(id) on delete cascade,
  following_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  check (follower_id <> following_id)
);

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.users(id) on delete cascade,
  title_id uuid references public.titles(id) on delete set null,
  body text not null check (char_length(body) between 1 and 1000),
  tags text[] not null default '{}',
  feeling text check (feeling is null or feeling in ('like', 'love', 'wow', 'haha', 'sad', 'angry')),
  visibility text not null default 'public' check (visibility in ('public', 'followers', 'private')),
  spoiler boolean not null default false,
  comments_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_images (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  url text not null,
  sort_order smallint not null default 0 check (sort_order between 0 and 4)
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null unique references public.posts(id) on delete cascade,
  title_id uuid not null references public.titles(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  created_at timestamptz not null default now(),
  unique (title_id, user_id)
);

create table if not exists public.post_likes (
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.post_comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  parent_id uuid references public.post_comments(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_shares (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.saved_movies (
  user_id uuid not null references public.users(id) on delete cascade,
  title_id uuid not null references public.titles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, title_id)
);

create table if not exists public.watchlist (
  user_id uuid not null references public.users(id) on delete cascade,
  title_id uuid not null references public.titles(id) on delete cascade,
  status text not null default 'planned' check (status in ('planned', 'watching', 'watched')),
  created_at timestamptz not null default now(),
  primary key (user_id, title_id)
);

create table if not exists public.user_movie_interactions (
  user_id uuid not null references public.users(id) on delete cascade,
  title_id uuid not null references public.titles(id) on delete cascade,
  interested boolean not null default false,
  reminder boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (user_id, title_id)
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_id uuid not null references public.users(id) on delete cascade,
  actor_id uuid references public.users(id) on delete cascade,
  type text not null check (type in ('like', 'comment', 'follow', 'mention', 'rating')),
  entity_id uuid,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.shoutbox_messages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null default 'text' check (type in ('text', 'image', 'voice')),
  body text check (body is null or char_length(body) <= 2000),
  media_url text,
  duration integer check (duration is null or duration between 0 and 600),
  created_at timestamptz not null default now(),
  check (body is not null or media_url is not null)
);

create table if not exists public.shoutbox_reactions (
  message_id uuid not null references public.shoutbox_messages(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  reaction text not null default 'love' check (reaction in ('love', 'fire', 'laugh')),
  primary key (message_id, user_id)
);

create index if not exists posts_created_at_idx on public.posts(created_at desc);
create index if not exists posts_author_idx on public.posts(author_id, created_at desc);
create index if not exists comments_post_idx on public.post_comments(post_id, created_at);
create index if not exists notifications_recipient_idx on public.notifications(recipient_id, read, created_at desc);
create index if not exists shoutbox_created_at_idx on public.shoutbox_messages(created_at desc);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at before update on public.users for each row execute function public.set_updated_at();
drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at before update on public.posts for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  requested_username text;
begin
  requested_username := lower(regexp_replace(coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)), '[^a-zA-Z0-9_]', '', 'g'));
  if char_length(requested_username) < 3 then requested_username := 'user_' || substr(new.id::text, 1, 8); end if;
  insert into public.users (id, email, username)
  values (new.id, coalesce(new.email, ''), requested_username)
  on conflict (id) do nothing;
  insert into public.profiles (user_id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', requested_username))
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.create_social_notification()
returns trigger language plpgsql security definer set search_path = '' as $$
declare target_user uuid;
declare notification_type text;
declare target_entity uuid;
declare actor_user uuid;
begin
  if tg_table_name = 'post_likes' then
    select author_id into target_user from public.posts where id = new.post_id;
    notification_type := 'like'; target_entity := new.post_id; actor_user := new.user_id;
  elsif tg_table_name = 'post_comments' then
    select author_id into target_user from public.posts where id = new.post_id;
    notification_type := 'comment'; target_entity := new.post_id; actor_user := new.user_id;
  elsif tg_table_name = 'follows' then
    target_user := new.following_id; notification_type := 'follow'; target_entity := new.follower_id; actor_user := new.follower_id;
  elsif tg_table_name = 'reviews' then
    select author_id into target_user from public.posts where id = new.post_id;
    notification_type := 'rating'; target_entity := new.post_id; actor_user := new.user_id;
  end if;
  if target_user is not null and target_user <> actor_user then
    insert into public.notifications(recipient_id, actor_id, type, entity_id)
    values (target_user, actor_user, notification_type, target_entity);
  end if;
  return new;
end;
$$;

drop trigger if exists notify_post_like on public.post_likes;
create trigger notify_post_like after insert on public.post_likes for each row execute function public.create_social_notification();
drop trigger if exists notify_post_comment on public.post_comments;
create trigger notify_post_comment after insert on public.post_comments for each row execute function public.create_social_notification();
drop trigger if exists notify_follow on public.follows;
create trigger notify_follow after insert on public.follows for each row execute function public.create_social_notification();
drop trigger if exists notify_review on public.reviews;
create trigger notify_review after insert on public.reviews for each row execute function public.create_social_notification();

alter table public.users enable row level security;
alter table public.profiles enable row level security;
alter table public.genres enable row level security;
alter table public.countries enable row level security;
alter table public.languages enable row level security;
alter table public.titles enable row level security;
alter table public.movie_genres enable row level security;
alter table public.movie_countries enable row level security;
alter table public.movie_languages enable row level security;
alter table public.follows enable row level security;
alter table public.posts enable row level security;
alter table public.post_images enable row level security;
alter table public.reviews enable row level security;
alter table public.post_likes enable row level security;
alter table public.post_comments enable row level security;
alter table public.post_shares enable row level security;
alter table public.saved_movies enable row level security;
alter table public.watchlist enable row level security;
alter table public.user_movie_interactions enable row level security;
alter table public.notifications enable row level security;
alter table public.shoutbox_messages enable row level security;
alter table public.shoutbox_reactions enable row level security;

drop policy if exists "Public profiles are readable" on public.users;
create policy "Public profiles are readable" on public.users for select using (true);
drop policy if exists "Users update themselves" on public.users;
create policy "Users update themselves" on public.users for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists "Profiles are readable" on public.profiles;
create policy "Profiles are readable" on public.profiles for select using (true);
drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile" on public.profiles for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Genres are readable" on public.genres;
create policy "Genres are readable" on public.genres for select using (true);
drop policy if exists "Countries are readable" on public.countries;
create policy "Countries are readable" on public.countries for select using (true);
drop policy if exists "Languages are readable" on public.languages;
create policy "Languages are readable" on public.languages for select using (true);
drop policy if exists "Titles are readable" on public.titles;
create policy "Titles are readable" on public.titles for select using (true);
drop policy if exists "Movie genres are readable" on public.movie_genres;
create policy "Movie genres are readable" on public.movie_genres for select using (true);
drop policy if exists "Movie countries are readable" on public.movie_countries;
create policy "Movie countries are readable" on public.movie_countries for select using (true);
drop policy if exists "Movie languages are readable" on public.movie_languages;
create policy "Movie languages are readable" on public.movie_languages for select using (true);

drop policy if exists "Follows are readable" on public.follows;
create policy "Follows are readable" on public.follows for select using (true);
drop policy if exists "Users manage own follows" on public.follows;
create policy "Users manage own follows" on public.follows for all to authenticated using (auth.uid() = follower_id) with check (auth.uid() = follower_id);

drop policy if exists "Public posts are readable" on public.posts;
create policy "Public posts are readable" on public.posts for select using (visibility = 'public' or author_id = auth.uid());
drop policy if exists "Users create own posts" on public.posts;
create policy "Users create own posts" on public.posts for insert to authenticated with check (auth.uid() = author_id);
drop policy if exists "Users update own posts" on public.posts;
create policy "Users update own posts" on public.posts for update to authenticated using (auth.uid() = author_id) with check (auth.uid() = author_id);
drop policy if exists "Users delete own posts" on public.posts;
create policy "Users delete own posts" on public.posts for delete to authenticated using (auth.uid() = author_id);

drop policy if exists "Post images are readable" on public.post_images;
create policy "Post images are readable" on public.post_images for select using (true);
drop policy if exists "Authors manage post images" on public.post_images;
create policy "Authors manage post images" on public.post_images for all to authenticated
using (exists(select 1 from public.posts p where p.id = post_id and p.author_id = auth.uid()))
with check (exists(select 1 from public.posts p where p.id = post_id and p.author_id = auth.uid()));

drop policy if exists "Reviews are readable" on public.reviews;
create policy "Reviews are readable" on public.reviews for select using (true);
drop policy if exists "Users manage own reviews" on public.reviews;
create policy "Users manage own reviews" on public.reviews for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Likes are readable" on public.post_likes;
create policy "Likes are readable" on public.post_likes for select using (true);
drop policy if exists "Users manage own likes" on public.post_likes;
create policy "Users manage own likes" on public.post_likes for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Comments are readable" on public.post_comments;
create policy "Comments are readable" on public.post_comments for select using (true);
drop policy if exists "Users create comments" on public.post_comments;
create policy "Users create comments" on public.post_comments for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Users manage own comments" on public.post_comments;
create policy "Users manage own comments" on public.post_comments for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users delete own comments" on public.post_comments;
create policy "Users delete own comments" on public.post_comments for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "Users create own shares" on public.post_shares;
create policy "Users create own shares" on public.post_shares for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Users read own saved movies" on public.saved_movies;
create policy "Users read own saved movies" on public.saved_movies for select to authenticated using (auth.uid() = user_id);
drop policy if exists "Users manage own saved movies" on public.saved_movies;
create policy "Users manage own saved movies" on public.saved_movies for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own watchlist" on public.watchlist;
create policy "Users manage own watchlist" on public.watchlist for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage movie interactions" on public.user_movie_interactions;
create policy "Users manage movie interactions" on public.user_movie_interactions for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users read own notifications" on public.notifications;
create policy "Users read own notifications" on public.notifications for select to authenticated using (auth.uid() = recipient_id);
drop policy if exists "Users update own notifications" on public.notifications;
create policy "Users update own notifications" on public.notifications for update to authenticated using (auth.uid() = recipient_id) with check (auth.uid() = recipient_id);

drop policy if exists "Shoutbox is publicly readable" on public.shoutbox_messages;
create policy "Shoutbox is publicly readable" on public.shoutbox_messages for select using (true);
drop policy if exists "Authenticated users send messages" on public.shoutbox_messages;
create policy "Authenticated users send messages" on public.shoutbox_messages for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Users delete own messages" on public.shoutbox_messages;
create policy "Users delete own messages" on public.shoutbox_messages for delete to authenticated using (auth.uid() = user_id);
drop policy if exists "Shoutbox reactions are readable" on public.shoutbox_reactions;
create policy "Shoutbox reactions are readable" on public.shoutbox_reactions for select using (true);
drop policy if exists "Users manage own reactions" on public.shoutbox_reactions;
create policy "Users manage own reactions" on public.shoutbox_reactions for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

grant usage on schema public to anon, authenticated;
grant select on public.genres, public.countries, public.languages, public.titles, public.movie_genres, public.movie_countries, public.movie_languages to anon, authenticated;
grant select on public.users, public.profiles, public.posts, public.post_images, public.reviews, public.post_likes, public.post_comments, public.follows, public.shoutbox_messages, public.shoutbox_reactions to anon, authenticated;
grant insert, update, delete on public.users, public.profiles, public.follows, public.posts, public.post_images, public.reviews, public.post_likes, public.post_comments, public.post_shares, public.saved_movies, public.watchlist, public.user_movie_interactions, public.notifications, public.shoutbox_messages, public.shoutbox_reactions to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public) values
  ('avatars', 'avatars', true),
  ('post-media', 'post-media', true),
  ('shoutbox-media', 'shoutbox-media', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public media is readable" on storage.objects;
create policy "Public media is readable" on storage.objects for select using (bucket_id in ('avatars', 'post-media', 'shoutbox-media'));
drop policy if exists "Users upload media" on storage.objects;
create policy "Users upload media" on storage.objects for insert to authenticated with check (bucket_id in ('avatars', 'post-media', 'shoutbox-media') and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "Users manage own media" on storage.objects;
create policy "Users manage own media" on storage.objects for update to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
drop policy if exists "Users delete own media" on storage.objects;
create policy "Users delete own media" on storage.objects for delete to authenticated using (owner_id = auth.uid()::text);

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'shoutbox_messages') then
    alter publication supabase_realtime add table public.shoutbox_messages;
  end if;
end $$;

insert into public.genres (name, slug) values
  ('Action','action'),('Adventure','adventure'),('Animation','animation'),('Comedy','comedy'),
  ('Crime','crime'),('Documentary','documentary'),('Drama','drama'),('Fantasy','fantasy'),
  ('Horror','horror'),('Mystery','mystery'),('Romance','romance'),('Sci-Fi','scifi'),
  ('Thriller','thriller'),('War','war'),('Western','western')
on conflict (slug) do nothing;
