"use client";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Bell, CalendarDays, ChevronRight, CircleHelp, Compass, Flame, Globe2, Home, Info, List, Menu, MessageCircle, Plus, Settings, Star, User, X } from "lucide-react";
import { useState } from "react";
import { publicAsset } from "@/lib/assets";

const nav = [{ href: "/home", label: "Home", icon: Home }, { href: "/explore", label: "Explore", icon: Compass }, { href: "/create-post", label: "", icon: Plus }, { href: "/shoutbox", label: "Shoutbox", icon: MessageCircle }, { href: "/profile/shahrieremon", label: "Profile", icon: User }];
const menu = [{ href: "/movies/upcoming", label: "Upcoming Movies", sub: "Never miss what’s coming next", icon: CalendarDays }, { href: "/movies/popular", label: "Most Popular", sub: "What everyone’s watching", icon: Flame }, { href: "/movies/highest-rated", label: "Highest Rated", sub: "Top rated by the community", icon: Star }, { href: "/explore", label: "Genre", sub: "Explore by movie genres", icon: Compass }, { href: "/explore/country/south-korea", label: "Country or Language", sub: "Movies from around the world", icon: Globe2 }, { href: "/movie-list", label: "Movie List", sub: "Curated collections", icon: List }];

export function Header({ back = false }: { back?: boolean }) {
  const [open, setOpen] = useState(false);
  return <><header className="topbar"><button className="icon-btn" onClick={() => back ? history.back() : setOpen(true)} aria-label={back ? "Go back" : "Open menu"}>{back ? <ChevronRight style={{ transform: "rotate(180deg)" }} /> : <Menu size={30} />}</button><Link className="brand" href="/home"><Image src={publicAsset("/brand/scenora-logo.png")} width={706} height={313} alt="SCENORA" priority /></Link><Link className="icon-btn" href="/notifications" aria-label="Notifications"><Bell/><i className="notif-dot" /></Link></header>{open && <SideMenu close={() => setOpen(false)} />}</>;
}
function SideMenu({ close }: { close: () => void }) { return <div className="side-overlay" onClick={close}><aside className="side-menu" onClick={e => e.stopPropagation()}><button className="icon-btn" style={{ marginLeft: "auto" }} onClick={close}><X size={32}/></button><Image src={publicAsset("/brand/scenora-logo.png")} width={706} height={313} alt="SCENORA" style={{ width: 215, height: 70, objectFit: "contain" }}/><Link href="/profile/shahrieremon" className="menu-item card"><Image className="avatar" src="https://i.pravatar.cc/160?img=68" width={60} height={60} alt=""/><span><b>Shahrier Emon</b><small>@shahrieremon</small></span><ChevronRight/></Link>{menu.map(({ href,label,sub,icon:Icon })=><Link className="menu-item card" href={href} key={label}><Icon className="orange"/><span><b>{label}</b><small>{sub}</small></span><ChevronRight/></Link>)}<hr style={{ borderColor: "#333" }}/><Link className="menu-item" href="/settings"><Settings/><span>Settings</span><ChevronRight/></Link><Link className="menu-item" href="/help"><CircleHelp/><span>Help & Support</span><ChevronRight/></Link><Link className="menu-item" href="/about"><Info/><span>About Scenora</span><ChevronRight/></Link><Link className="menu-item card" href="/login" style={{ color: "#ff4d5d" }}><X/><span>Sign Out</span><ChevronRight/></Link></aside></div> }
export function BottomNav() { const path = usePathname(); return <nav className="bottom-nav">{nav.map(({href,label,icon:Icon},i)=><Link key={href} href={href} className={`nav-link ${i===2?"create-nav":""} ${path.startsWith(href)?"active":""}`}><Icon size={i===2?38:27}/>{label && <span>{label}</span>}</Link>)}</nav> }
export function Shell({ children, back = false, nav = true }: { children: React.ReactNode; back?: boolean; nav?: boolean }) { return <main className="app"><Header back={back}/>{children}{nav && <BottomNav/>}</main> }
